### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by 1041176461** [1041176461/abacus-ase#4]
# Features
- [ ] #2  check variable-cell optimization using ABACUS
- [ ] add KPT omitting for `kspacing` setting 
- [ ] optimize files parsing with `re` pacakage
